---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: flux-oci-demo
  namespace: flux-system
spec:
  url: oci://ghcr.io/juozasg/flux-oci-demo
  interval: 30s
  provider: generic
  ref:
    tag: latest
  secretRef:
    name: ghcr-auth

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-oci-demo
  namespace: flux-system
spec:
  interval: 30s
  path: ./clusters/demo
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-oci-demo
  targetNamespace: default
